In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_excel('fin_data_of_proj.xlsx')
df = df[:-11]
df

,Unnamed: 0,gara_id,application_name,author_id,builder_id,contractor_id,designer_id,engine_id,manager_id,status,...,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга,Target,life_cycle,today,real_life_cycle,percent_of_lifi_cycle,percent_of_life_cycle
0,0,729352,Заявка на гарантирование - 335,5.400012e+08,960340000376,9.603400e+11,0.0,2.210400e+11,1.904400e+11,NaN,...,1.0,0.060174,5.733126,3.488284,0,395,2024-11-01,729,1.845570,1.845570
1,1,790750,Заявка на гарантирование - 334,4.044001e+10,960340000376,9.603400e+11,0.0,2.210400e+11,1.904400e+11,NaN,...,1.0,0.060174,5.733126,3.488284,0,639,2024-11-01,729,1.140845,1.140845
2,2,845821,Заявка на гарантирование - 407,8.034001e+10,60340004172,6.034000e+10,0.0,1.304400e+11,2.109400e+11,NaN,...,1.0,0.929396,20.794199,0.550207,0,274,2024-11-01,508,1.854015,1.854015
3,3,781580,Заявка на гарантирование - 379,5.114001e+10,981040003722,9.810400e+11,0.0,7.054001e+10,2.109400e+11,NaN,...,1.0,0.020449,1331.828571,5.548625,0,426,2024-11-01,742,1.741784,1.741784
4,4,746713,Заявка на гарантирование - 373,9.207400e+11,80440009616,8.044001e+10,0.0,2.208400e+11,2.202400e+11,NaN,...,1.0,0.000000,inf,inf,0,275,2024-11-01,575,2.090909,2.090909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,214,1152403,Заявка на гарантирование - 484,1.704400e+11,131240018048,1.312400e+11,0.0,2.003400e+11,1.709400e+11,NaN,...,1.0,0.000000,26.373242,inf,0,365,2024-11-01,246,0.673973,0.673973
207,215,1130533,Заявка на гарантирование - 478,8.104000e+10,50640012251,5.064001e+10,0.0,2.111400e+11,2.201400e+11,NaN,...,1.0,0.331792,inf,0.823126,0,305,2024-11-01,281,0.921311,0.921311
208,216,1124311,Заявка на гарантирование - 476,7.074002e+10,170840003753,1.708400e+11,0.0,1.411400e+11,2.004400e+11,NaN,...,1.0,5.479264,-inf,-0.039945,0,701,2024-11-01,324,0.462197,0.462197
209,217,1159397,Заявка на гарантирование - 485,3.104000e+10,31040001233,3.104000e+10,0.0,1.607400e+11,2.401400e+11,NaN,...,1.0,0.000000,inf,inf,0,304,2024-11-01,183,0.601974,0.601974


In [48]:
df = df.drop(['Unnamed: 0', 'application_name', 'author_id', 'contractor_id', 'designer_id', 'engine_id', 'status',
              'decision_date', 'region_name', 'type', 'turn', 'period_month', 'build_qty', 'share_cost', 'comm_cost',
              'prolongation', 'state_id', 'annul_date', 'state_name', 'дата фин данных', 'percent_of_lifi_cycle'], axis=1)

## Models Testing

In [79]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix, 
    roc_auc_score, roc_curve
)

# Define the target variable (y) and features (X)
y = df['Target']
X = df.drop(columns=['Target'])
X.replace([np.inf, -np.inf], np.nan, inplace=True)

# Identify non-numeric columns
non_numeric_cols = X.select_dtypes(include=['object', 'datetime', 'timedelta']).columns

# Apply LabelEncoder to non-numeric columns           
label_encoder = LabelEncoder()
for col in non_numeric_cols:
    X[col] = label_encoder.fit_transform(X[col].astype(str))

# Handle missing values using SimpleImputer (fill with median)
imputer = SimpleImputer(strategy='median')
X_imputed_encoded = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed_encoded, y, test_size=0.2, random_state=42)

# Initialize ensemble models
models = {
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Bagging": BaggingClassifier(),
}

# Train models and collect predictions and feature importances
feature_importances = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    
    # Store feature importance if available
    if hasattr(model, 'feature_importances_'):
        feature_importances[name] = model.feature_importances_

    # Predict and evaluate
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred):.2f}")
    print(f"{name} Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
    print(f"{name} ROC AUC: {roc_auc_score(y_test, y_prob):.2f}\n")


plt.tight_layout()
plt.show()

Random Forest Accuracy: 0.86
Random Forest Confusion Matrix:
[[36  0]
 [ 6  1]]

Random Forest ROC AUC: 0.79

Gradient Boosting Accuracy: 0.81
Gradient Boosting Confusion Matrix:
[[34  2]
 [ 6  1]]

Gradient Boosting ROC AUC: 0.75

AdaBoost Accuracy: 0.72
AdaBoost Confusion Matrix:
[[30  6]
 [ 6  1]]

AdaBoost ROC AUC: 0.52

Bagging Accuracy: 0.86
Bagging Confusion Matrix:
[[36  0]
 [ 6  1]]

Bagging ROC AUC: 0.58



C:\Users\Norynbayev\AppData\Local\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


<Figure size 640x480 with 0 Axes>

## Feature Importance


In [67]:
from matplotlib.backends.backend_pdf import PdfPages

num_features = X.shape[1]
fig, axes = plt.subplots(len(feature_importances), 1, figsize=(40, 20 * len(feature_importances)))

with PdfPages("feature_importances.pdf") as pdf:
    for idx, (name, importance) in enumerate(feature_importances.items()):
        axes[idx].barh(X.columns, importance)
        axes[idx].set_title(f"{name} Feature Importance")
        axes[idx].set_xlabel("Importance Score")
        axes[idx].set_ylabel("Features")
        
    pdf.savefig(fig)
    plt.close(fig) 

In [68]:
X_test

,gara_id,builder_id,manager_id,city_id,network,start_date,end_date,class,flat_area,build_floor,...,Коэффициент финансового левериджа,Коэффициент финансовой независимости,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга,life_cycle,today,real_life_cycle,percent_of_life_cycle
30,198.0,9.603400e+11,1.606400e+11,18194.0,4.0,6.0,5.0,4.0,8948.40,65.0,...,5.236752,0.190958,1.000000,0.623296,-3.579692,-0.091385,516.0,0.0,2481.0,4.808140
173,93.0,1.034000e+10,2.002400e+11,18277.0,20.0,88.0,103.0,4.0,18955.35,48.0,...,8.638802,0.115757,1.000000,0.295723,1.522332,0.608822,671.0,0.0,1288.0,1.919523
140,43.0,6.014000e+10,1.702400e+11,18178.0,4.0,11.0,17.0,4.0,12015.51,65.0,...,18.578259,0.053826,1.000000,0.000000,1.522332,0.155298,708.0,0.0,2328.0,3.288136
75,7.0,1.105400e+11,1.906400e+11,18194.0,3.0,34.0,45.0,4.0,22101.80,18.0,...,11.883087,0.084153,1.000000,0.138312,1.522332,7.945981,695.0,0.0,1866.0,2.684892
60,184.0,9.010400e+11,2.106400e+11,18178.0,3.0,139.0,126.0,4.0,10854.86,39.0,...,52.529763,0.019037,1.000000,6.570286,1.522332,0.108103,365.0,0.0,798.0,2.186301
208,1124311.0,1.708400e+11,2.004400e+11,18194.0,60.0,177.0,184.0,4.0,31440.78,47.0,...,6.597274,0.151578,1.000000,5.479264,1.522332,-0.039945,701.0,0.0,324.0,0.462197
45,194.0,1.106400e+11,1.610400e+11,18194.0,3.0,58.0,78.0,4.0,15350.64,5.0,...,2.993028,0.334110,1.000000,0.238986,1.522332,0.155298,674.0,0.0,1486.0,2.204748
183,1124232.0,1.105400e+11,2.108400e+11,18178.0,59.0,183.0,166.0,4.0,7217.35,48.0,...,5.682418,0.175981,1.000000,1.663461,-819.395349,-0.007622,214.0,0.0,226.0,1.056075
9,892091.0,1.105400e+11,2.108400e+11,18178.0,60.0,163.0,152.0,4.0,16162.59,20.0,...,3.666575,0.272734,1.000000,1.271609,-25.765597,-0.017271,366.0,0.0,518.0,1.415301
100,199.0,6.054001e+10,2.002400e+11,18178.0,31.0,103.0,78.0,4.0,11410.70,48.0,...,2.726757,0.366736,1.000000,0.063511,1.522332,0.070352,400.0,0.0,1212.0,3.030000


In [74]:
model = RandomForestClassifier(n_estimators = 200, max_depth = 100000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


In [75]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [71]:
y_test

30     0
173    1
140    0
75     0
60     0
208    0
45     0
183    0
9      1
100    0
137    0
204    0
156    0
82     0
15     0
200    0
167    0
18     0
209    0
86     0
79     0
55     0
148    0
206    0
150    0
143    1
25     1
104    0
16     0
177    1
135    0
126    0
109    0
68     0
73     0
147    0
181    0
96     0
189    0
93     1
115    0
163    0
195    1
Name: Target, dtype: int64